version: '3'

services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile"
    command: --shm-size 8gb
    volumes:
      - ./src:/workspace/src:cached
      - ./data:/workspace/data
      # mount output dir
      - /mnt/d/experiments/:/outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
